spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            sample-feign:
              - uri: http://www.google.com
    loadbalancer:
      cache:
        enabled: false
      retry:
        enabled: false
